default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresql
  username: pguser
  password: pgpass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webhook_debugger_development

test:
  <<: *default
  database: webhook_debugger_test

production:
  <<: *default
  database: webhook_debugger_production
